version: '3'

services:
  app:
    build: .
    env_file: .env

  s3:
    image: quay.io/minio/minio
    env_file: .env
    command: server /data

  mq:
    image: rabbitmq:4.0-management-alpine
    env_file: .env
