version: '2'

services:
  app:
    build: .
    volumes:
      - ".:/var/myapp"
    environment:
      - "S3_ENDPOINT=${S3_ENDPOINT}"
      - "S3_REGION=${S3_REGION}"
      - "S3_ACCESS_KEY=${S3_ACCESS_KEY}"
      - "S3_SECRET_KEY=${S3_SECRET_KEY}"
      - "S3_BUCKET=${S3_BUCKET}"
      - "S3_FOLDER=${S3_FOLDER}"
    command: /bin/sh -c "pipenv run lint && pipenv run test"
    depends_on:
      - "s3"

  s3:
    image: minio/minio
    volumes:
      - "s3:/export"
    environment:
      - "MINIO_ACCESS_KEY=${S3_ACCESS_KEY}"
      - "MINIO_SECRET_KEY=${S3_SECRET_KEY}"
      - "MINIO=REGION=${S3_REGION}"
    command: server /export

volumes:
  s3:
    driver: local
