version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - "..:/var/myapp"
    env_file: .env

  s3:
    image: quay.io/minio/minio
    ports:
      - 9001:9001
    env_file: .env
    command: server /data --console-address ':9001'
